[model]
net = "resnet18"
pretrained = true
transfer = false

[training]
lr = 0.001
momentum = 0.9
num_epochs = 5
batch_size = 10

[device]
nvidia = 0

[data]
num_val = 8
which_data = "dataset0a"
train_data = "train"
test_data = "test"
generated = false
